import { EnquiryForm } from "../components/EnquiryForm";
import { Gallery } from "../components/Gallery";
import { SectionHeader } from "../components/SectionHeader";
import { partners, site } from "../data/site";

const workshopCards = [["PARAI", "Learn the fundamentals, rhythms and techniques of Parai."], ["FOLK PERFORMANCE", "Explore movement, rhythm and collective performance."], ["CULTURAL WORKSHOPS", "Experience the history, context and living traditions behind folk arts."], ["CUSTOM PROGRAMS", "Workshops designed for schools, colleges, organisations and communities."]];

export default function Home() { return <main>
  <section className="hero"><img src={site.heroImage} alt="Agni Arts Parai performance" /><div className="hero-shade"></div><div className="container hero-content"><p className="eyebrow hero-brand">AGNI ARTS</p><h1><span>The rhythm</span><span className="indent">of</span><span>resistance</span></h1><p className="hero-intro">Reviving folk arts. Reimagining traditions. Carrying the fire forward.</p><p className="hero-description">Agni Arts is a collective of artists united by a shared commitment to reviving and celebrating folk art forms. Through learning, performance, and community, we create spaces where art is experienced, shared, and carried into the future.</p><div className="button-row"><a className="button" href="#about">Explore Agni <span>↗</span></a><a className="text-link" href="#workshops">Join a workshop <span>↗</span></a></div></div><div className="scroll-note">SCROLL TO DISCOVER <span>↓</span></div></section>
  <section className="intro section container" id="about"><div className="intro-text"><SectionHeader number="01" kicker="THE FIRE WE CARRY" title="We are Agni." /><p>A collective of artists, performers, teachers and learners working to revive diminishing folk arts and carry them into the future.</p><p></p><p>We believe tradition flourishes when it is shared. Every workshop, every performance, and every new learner strengthens a legacy that continues to inspire communities across generations.</p></div><div className="image-frame intro-image"><img src={site.introImage} alt="Agni Arts collective" /><span>PHOTO SLOT — update in `data/site.ts`</span></div></section>
  <section className="stats"><div className="container stats-grid">{[["8+", "Years of the journey"], ["200+", "Students trained"], ["60+", "Performance venues"], ["Monthly,Weekly", "Classes"]].map(([number, label]) => <div key={label}><strong>{number}</strong><span>{label}</span></div>)}</div></section>
  <section className="trainer section container" id="trainer"><div className="trainer-copy"><SectionHeader number="02" kicker="MEET OUR TRAINER" title="Iniyaal" /><p>Iniyaal has been learning Parai for the past ten years, having started at a young age. Growing up with patai is an integral part of her life. As one of Agni&apos;s founding trainers, she has played a key role in shaping its learning community from the very beginning.</p><p>Alongside Parai, Iniyaal is a Western vocalist, theatre artist, ballet dancer, and practitioner of Silambam. Exploring different art forms has given her a unique perspective on movement, music, and expression.</p><p>She has also collaborated with the Indian Music Experience Museum and Museum of art of photography, contributing to initiatives that bring traditional art forms into cultural and educational spaces, helping make them more accessible to wider audiences.</p></div><div className="image-frame trainer-image"><img src={site.introImage} alt="Iniyaal with Agni Arts" /><span>PHOTO SLOT — update in `data/site.ts`</span></div></section>
  <section className="parai section container" id="parai"><div><SectionHeader number="02" kicker="THE ART" title="Parai" /><h3>The rhythm that refuses to fade.</h3><p>Parai is often described as the mother of percussion instruments. Its sound carries memory, gathering, joy and collective movement.</p><a className="text-link" href="#parai">Discover the story <span>↗</span></a></div><div className="image-frame parai-image"><img src={site.paraiImage} alt="Parai drum in performance" /><span>PHOTO SLOT — update in `data/site.ts`</span></div></section>
  <section className="story-band"><div className="container"><p className="eyebrow">03 — A CULTURAL NARRATIVE</p><h2>Birth &amp; evolution<br />of Parai.</h2><div className="story-copy"><p>Long before written history, rhythm was one of humanity&apos;s first languages. Across generations, the Parai emerged as one of the oldest percussion instruments of Tamil culture, accompanying harvests, celebrations, ceremonies, deaths and important community gatherings.</p><p>Over time, changing social structures altered how the instrument was perceived. Yet despite centuries of marginalization, Parai endured through the resilience of the communities who protected its traditions.</p><p>Today, Parai stands not only as an instrument but as a powerful expression of identity and resilience. Every rhythm carries stories that continue to echo through generations.</p></div><div className="from-to"><span>From survival</span><i>to expression.</i></div></div></section>
  <section className="why section container"><SectionHeader number="04" kicker="WHY PARAI?" title="A sound that gathers." /><div className="meaning-grid">{[["01", "Communication", "A rhythm used to communicate and gather communities."], ["02", "Protection", "Sound as a tool of warning and protection."], ["03", "Celebration", "Rhythm as part of collective celebration."], ["04", "Identity", "A living expression of community, history and culture."]].map(([number, title, text]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="academy section" id="academy"><div className="container" id="workshops"><SectionHeader number="05" kicker="THE ACADEMY" title="Learn the rhythm." /><p className="section-lede">Don&apos;t just watch folk art. Learn it. Feel it. Carry it forward.</p><div className="workshop-grid">{workshopCards.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p><a href="https://wa.me/919740781481" aria-label={`Explore ${title}`}>↗</a></article>)}</div><a className="button" href="https://wa.me/919740781481">Join a workshop <span>↗</span></a></div></section>
  <section className="locations section container"><div><p className="eyebrow">06 — WHERE WE GATHER</p><h2>The rhythm travels.</h2><p>Agni conducts workshops every month across Bengaluru, Hosur, Chennai and different parts of Tamil Nadu.</p><a className="text-link" href="https://wa.me/919740781481">View workshop enquiries <span>↗</span></a></div><div className="map-art" aria-label="Workshop locations"><b>BENGALURU</b><b>HOSUR</b><b>CHENNAI</b><b>TAMIL NADU</b><span className="ring ring-1"></span><span className="ring ring-2"></span><span className="ring ring-3"></span></div></section>
  <section className="process section container"><SectionHeader number="07" kicker="THE PROCESS" title="Feel it. Carry it." /><div className="process-grid">{[["01", "Discover", "Experience the history and cultural context behind the art."], ["02", "Learn", "Understand rhythm, technique and movement through hands-on training."], ["03", "Practice", "Build confidence through regular practice."], ["04", "Perform", "Take what you&apos;ve learned into real performances and public spaces."]].map(([n,t,d]) => <article key={t}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="performances section" id="performances"><div className="container performances-header"><p className="eyebrow">08 — ON THE MOVE</p><h2>We don&apos;t just teach the rhythm.<br /><em>We bring it to the world.</em></h2><p>From institutions and corporate spaces to public events and social-awareness programs, Agni has performed across Bengaluru, Hosur, Chennai and Tamil Nadu.</p></div><div className="container"><Gallery /></div><div className="container gallery-action"><a className="button" href="https://wa.me/919740781481">View all performances <span>↗</span></a></div></section>
  <section className="partners section container"><p className="eyebrow">AGNI HAS PERFORMED FOR</p><div>{partners.map((partner) => <span key={partner}>{partner}</span>)}</div><small>Names shown as supplied. Add approved logos later in the content layer.</small></section>
  <section className="instagram section container"><p className="eyebrow">09 — STAY CLOSE</p><h2>Follow the rhythm.</h2><div className="instagram-grid">{site.gallery.slice(0, 5).map((item) => <div key={item.src}><img src={item.src} alt={item.alt} loading="lazy" /></div>)}</div><a className="text-link" href={site.instagram}>Follow Agni <span>↗</span></a></section>
  <section className="final-cta"><div className="container"><p className="eyebrow">10 — JOIN THE MOVEMENT</p><h2>Want to be part<br />of the rhythm?</h2><div className="cta-options"><article><h3>Learn</h3><p>Join a workshop.</p><a className="button" href="https://wa.me/919740781481">Join a workshop ↗</a></article><article><h3>Experience</h3><p>Invite Agni for a performance.</p><a className="button button-outline" href="https://wa.me/919740781481">Book a performance ↗</a></article><article><h3>Collaborate</h3><p>Work with Agni on a cultural project.</p><a className="button button-outline" href="https://wa.me/919740781481">Start a conversation ↗</a></article></div></div></section>
  <section className="form-section" id="contact"><div className="container form-layout"><div><p className="eyebrow">MAKE AN ENQUIRY</p><h2>Start a conversation.</h2><p>Tell us how you&apos;d like to learn, perform or collaborate with Agni Arts.</p></div><EnquiryForm /></div></section>
</main>; }
